In [76]:
import pandas as pd
import numpy as np
from sklearn.compose import make_column_transformer

In [77]:
df = pd.DataFrame({"data1" : [12,34,2,5,np.nan],
"data2" : [np.nan,15,34,23,1]})
df

,data1,data2
0,12.0,NaN
1,34.0,15.0
2,2.0,34.0
3,5.0,23.0
4,NaN,1.0


In [78]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import SimpleImputer , IterativeImputer , KNNImputer
cl = make_column_transformer((SimpleImputer(),["data1"]),remainder='passthrough')
df1 = cl.fit_transform(df)
df1


array([[12.  ,   nan],
       [34.  , 15.  ],
       [ 2.  , 34.  ],
       [ 5.  , 23.  ],
       [13.25,  1.  ]])

In [79]:
it = IterativeImputer()
df2 = it.fit_transform(df)
df2

array([[12.        , 23.83933798],
       [34.        , 15.        ],
       [ 2.        , 34.        ],
       [ 5.        , 23.        ],
       [45.66287601,  1.        ]])

In [80]:
df3 = KNNImputer(n_neighbors=2).fit_transform(df)
df3

array([[12. , 28.5],
       [34. , 15. ],
       [ 2. , 34. ],
       [ 5. , 23. ],
       [19.5,  1. ]])